### ISSUE TITLE
VCF attack/AL wrong

### ISSUE THREAD

**Issue by ForDeckard** [ffont/ddrm-issues#22] opened 2018-05-16 08:51 UTC
in 1.2.4 there is always a bit of VCF attack even when the Attack is zet to zero. resulting in a short 'pwap'. Also the AL slider does not seem to work properly.

Test:

The first round is with the AL slider down, the second with the AL slide up. In 1.2.4 you can hear there is no difference.

1.2.3:

https://www.dropbox.com/s/m3cneqawd4hiw6j/VCF%20Attack%20firmware%201.2.3.mp3?dl=0

1.2.4:

https://www.dropbox.com/s/de486rdbimf0cff/VCF%20Attack%20firmware%201.2.4.mp3?dl=0

**Comment by ffont** [comment] 2018-05-20 16:09
I don't seem to be able to reproduce this problem, or I don't notice the short attack

**Comment by ForDeckard** [comment] 2018-05-25 15:12
I assume you can hear the difference in the posted examples right? I asked other users and they also weren't able to reproduce this. It seems like a faulty unit? Strange thing is though i really do not have this issue with 1.2.3...

**Comment by ForDeckard** [comment] 2018-06-02 06:54
could you test this:
I created a simple preset and added the bank. It's preset #1 Listen to the audio examples how it sounds in 1.2.4 and 1.2.3:

https://www.dropbox.com/sh/mpcv72neunvzuvg/AADVR4ClHCjLGnYT_8JY4V4va?dl=0

**Comment by ffont** [comment] 2018-06-04 08:23
I'll look at it as soon as I can

**Comment by ForDeckard** [comment] 2018-06-10 14:41
Have you been able to test this ?

**Comment by ffont** [comment] 2018-06-11 08:55
Hi I'm really sorry but I've been really busy and had only little time to play with DDRM so I did not look yet into reproducing the issue. I'll eventually but I can't tell you when. Probably next week.

**Comment by ForDeckard** [comment] 2018-06-18 20:41
HI ffont. Any progress? It will only take a few minutes, i would really like to know what is going on. Here is another short clip. Another user that listens to my samples said he had a hard time discerning the difference . 
https://www.dropbox.com/s/3kbtz2gsgh0bij3/Short%20example.mp3?dl=0

**Comment by ffont** [comment] 2018-06-20 17:12
Hi, 
I finally managed to do the test as explained in your instructions (loading the 2 firmwares and recording audio examples, using the provided patch with no modifications and without touching sliders). To my ears, both 1.2.3 and 1.2.4 sound the same (although I can tell the difference in your examples). My sound examples are in this ZIP file: [Attack experiment examples.zip](https://github.com/ffont/official-ddrm-issue-tracker/files/2120352/Attack.experiment.examples.zip)

**Comment by ForDeckard** [comment] 2018-06-20 17:22
Hi Frederick, thanks for testing this! You definitely do not have this issue, the attack sounds nice and snappy, even snappier then my 1.2.3. So that means the issue is with my DDRM. What do you suggest must be done to fix this?

**Comment by ffont** [comment] 2018-06-21 07:54
Hi, really I have no idea, I built a DIY DDRM myself and set up this page to help people report and organize issues, but I have no more experience nor connections to Black Corp and I only know basic electronics. In fact, DDRM was my first DIY synth I built. I'd suggest that you should directly contact Roman and Bob via facebook and paste a link to this issue. Also people like Ando and Steve might be able to help better than I.

The fact that (in your case) it sounds different depending on the firmware makes me think that the problem is no related with the hardware in voice cards or mother board. It could have to do with the way in which slider's signal is sampled. I know that in different firmware versions the way slider input is treated changes (with different resolutions and stuff). It might be that this in combination with some problem with the attack slider is causing the problem. In fact I just thought of a couple of things  you could try:

- Compare with layers A/B: if you move the mix slider to A and B layers, is the problem still there for both layers?
- Check the MIDI messages that your unit is outputting. You can use [this tool I made](https://ffont.github.io/resources/midiMonitor). Is the unit constantly outputting control change messages for the attack slider? (you'll need to check the DDRM MIDI specification to know which CC corresponds to attack). Maybe you have some jitter in your slider that prevents from going to attack 0 and the different firmware versions have different ways of dealing with that.

**Comment by ForDeckard** [comment] 2018-06-21 09:49
Hi Frederic,
I’m so very sorry, i assumed you were affiliated to black corporation, since Bob referred to your github and jumped into conclusions. I realise i pushed a bit as I felt there is a responsibility from Back Corp to help me out. My wrong! Thank you very much for your help and i will address Bob if it turns out to be a warranty issue of some kind. And I will try your suggestions.

**Comment by schillp5** [comment] 2018-10-16 16:16
is this still an issue or can this bug be closed?

**Comment by ffont** [comment] 2019-04-24 08:41
Closing as no further comments were made, assuming it is fixed or will be reopened.

**Closed as completed by ffont** 2019-04-24 08:41 UTC
